export const environment = {
  production: true,
  platformProviderApiBaseUrl: 'https://demy-web-service-production.up.railway.app/api/v1',
  usersEndpointPath: '/users',
  adminsEndpointPath: '/admins',
  teachersPath: '/teachers',
  platformProviderSignInEndpointPath: '/sign-in',
  platformProviderSignUpEndpointPath: '/sign-up',
  resetPasswordPath: '/reset-password',
  academyEndpointPath: '/academies',
  academicPeriodEndpointPath: "/academic-periods",
  studentsEndpointPath: "/students",
  enrollmentEndpointPath: "/enrollments",
  invoicesEndpointPath: "/invoices",
  paymentsEndpointPath: "/payments",
  financialTransactionsEndpointPath: "/financial-transactions",
  coursesEndpointPath: '/courses',
  classroomsEndpointPath: '/classrooms',
  weeklyScheduleEndpointPath: '/weekly-schedules',
  attendancesEndpointPath: '/attendance-record',
  classSessionsEndpointPath: '/class-sessions',
  attendanceReportEndpointPath: '/class-sessions/report',
  payEndpointPath: '/payments',
  intentEndpointPath: '/create-intent',
};
