export const environment = {
  production: false,
  platformProviderApiBaseUrl: 'http://localhost:8080',
  platformProviderSignInEndpointPath: '/api/v1/authentication/sign-in',
  platformProviderSignUpEndpointPath: '/api/v1/authentication/sign-up',
  platformProviderVerifyEndpointPath: '/api/v1/authentication/verify',
  platformProviderResendCodeEndpointPath: '/api/v1/authentication/resend-code',
  platformProviderAdminRegisterEndpointPath: '/api/v1/administrators',
  platformProviderAcademyRegisterEndpointPath: '/api/v1/academies',
  platformProviderRequestResetPasswordEndpointPath: '/api/v1/authentication/request-reset-password',
  platformProviderVerifyResetCodeEndpointPath: '/api/v1/authentication/verify-reset-code',
  platformProviderResetPasswordEndpointPath: '/api/v1/authentication/reset-password',
  platformProviderTeachersEndpointPath: '/api/v1/teachers',
  platformProviderCoursesEndpointPath: '/api/v1/courses',
  platformProviderClassroomsEndpointPath: '/api/v1/classrooms',
  platformProviderSchedulesEndpointPath: '/api/v1/schedules',
  platformProviderAcademicPeriodsEndpointPath: '/api/v1/academic-periods',
  platformProviderEnrollmentsEndpointPath: '/api/v1/enrollments',
  platformProviderStudentsEndpointPath: '/api/v1/students',
  platformProviderBillingAccountsEndpointPath: '/api/v1/billing-accounts',
  platformProviderTransactionsEndpointPath: '/api/v1/transactions',
  platformProviderReportsTransactionsEndpointPath: '/api/v1/reports/transactions',
  platformProviderClassAttendancesEndpointPath: '/api/v1/class-attendances',
};
